name: complex
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  asuka: ^1.0.4
  autotrie: ^0.4.1
  carousel_slider: ^3.0.0
  cloud_firestore: ^0.15.0
  cloud_functions: ^0.8.0
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  device_info: ^2.0.0
  equatable: ^2.0.0
  file_picker: ^2.1.7
  firebase_auth: ^0.19.0+1
  firebase_messaging: ^6.0.0
  firebase_storage: ^6.0.0
  flow_builder: ^0.0.2
  flutter_bloc: ^6.1.3
  flutter_colorpicker: ^0.4.0
  flutter_country_picker: ^0.1.6
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.0
  flutter_facebook_login: ^3.0.0
  flutter_keyboard_visibility: ^4.0.6
  flutter_phone_direct_caller: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_restart: ^0.0.3
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7
  freezed_annotation: ^0.12.0
  geocoding: ^1.0.5
  geolocator: ^6.0.0+4
  get: ^3.25.4
  google_maps_flutter: ^1.0.6
  google_maps_place_picker: ^1.0.1
  google_sign_in: ^4.5.9
  horizontal_data_table: ^2.5.2
  injector: ^2.0.0
  intl: ^0.16.1
  json_annotation: ^3.1.1
  location: ^3.2.4
  logger: ^1.0.0
  material_design_icons_flutter: ^4.0.5955
  multi_select_flutter: ^4.0.0
  overlay_support: ^1.2.1
  path_provider: ^1.6.9
  pin_code_fields: ^7.0.0
  provider: ^4.0.1
  qr_code_scanner: ^0.4.0
  reorderables: ^0.4.1
  rxdart: ^0.27.1
  sembast: ^3.0.2
  shared_preferences: ^0.5.3
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.0.0
  syncfusion_flutter_barcodes: ^19.1.58
  timeago: ^3.0.2
  video_player: ^2.1.1
  webview_flutter: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  freezed: ^0.12.7
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dailyneeds/
    - assets/help/
    - assets/homerepairs/
    - assets/services/
    - assets/shopping/
    - assets/icons/
    - assets/icons/order/
    - assets/images/tileimages/L1/
    - assets/images/tileimages/L2/
    - assets/other_util/zip_codes.json

fonts:
  - family: Merriweather
    fonts:
      - asset: fonts/Merriweather-Regular.ttf
