name: complex
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  flutter_bloc: ^7.0.0
  injector: ^2.0.0
  provider: ^5.0.0
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^1.1.2
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.0.0
  flutter_country_picker: ^0.1.6
  cloud_functions: ^1.0.5
  cloud_firestore: ^1.0.7
  pin_code_fields: ^7.0.0
  intl: ^0.17.0
  syncfusion_flutter_barcodes: ^19.1.58
  google_maps_flutter: ^2.0.3
  google_maps_place_picker: ^2.0.0-nullsafety.3
  geocoding: ^2.0.0
  file_picker: ^3.0.1
  video_player: ^2.1.1
  firebase_messaging: ^10.0.0
  device_info: ^2.0.0
  overlay_support: ^1.2.1
  sembast: ^3.0.2
  path_provider: ^2.0.1
  flutter_restart: ^0.0.3
  carousel_slider: ^3.0.0
  geolocator: ^7.0.3
  get: ^3.25.4
  flutter_colorpicker: ^0.4.0
  flutter_spinkit: ^5.0.0
  flutter_datetime_picker: ^1.5.1
  equatable: ^2.0.0
  flutter_easyloading: ^3.0.0
  asuka: ^1.0.4
  logger: ^1.0.0
  location: ^4.3.0
  freezed: ^0.14.2
  rxdart: ^0.27.1
  flow_builder: ^0.0.3
  webview_flutter: ^2.0.9
  animate_do: ^2.0.0
  dartz: ^0.9.2
  firebase_storage: ^9.0.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_phone_direct_caller: ^2.0.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.7
  freezed_annotation: ^0.14.2
  horizontal_data_table: ^3.4.2
  json_annotation: ^4.0.1
  material_design_icons_flutter: ^4.0.5955
  multi_select_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  reorderables: ^0.4.1
  shimmer: ^2.0.0
  timeago: ^3.1.0
  autotrie: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/other_util/zip_codes.json
    - assets/listViewIcons/

fonts:
  - family: Merriweather
    fonts:
      - asset: fonts/Merriweather-Regular.ttf